### ISSUE TITLE
Starting a Smallworld 4 session

### ISSUE THREAD

**Issue by hetsch** [OpenSmallworld/magik-vscode#3]
Hi,

first, thank's for this nice extension! Please bare with me if this is a dump question, because I'm a novice in the Smallworld ecosystem, although would say that I have some experience in coding and VSCode.

I have a question regarding the start of a Smallworld 4 session with your extension. I think I followed your steps in the ReadMe.md closely, but somehow VSCode does not attach to the SM session and I do not get a Magik prompt (or something else) after I issued the following command in the VSCode Terminal: `X:\swgis\product\bin\x86\gis.exe -a X:\...\gis_aliases -e X:\...\environment.bat swaf`. This command is taken from my EMACS environment, that works fine so far. 

The SM programm starts up fine but VSCode just does not do anything. My .vscode/settings.json looks like this:

```
{
    "magik-vscode.magikProcessName": "sw_magik_win32.exe",
    "terminal.integrated.scrollback": 20000,
    "files.encoding": "iso88591",
    "editor.formatOnType": true
}
```

I can see a process called `Sw_magik_win32.exe` in the TaskManager, so this should be fine too.

Any ideas are more than welcome.

**Comment by gepaulwarwicker** [comment]
You do not start the session directly from the shell manually. You need to use F2-Z, or the way I personally start sessions is to use F1, then type "start magik". You will see two options "Magik Start Session" and "Magik Start Debug Session". Choosing either of these will prompt you for the location of the gis_aliases and runalias.exe files.

-paul

**Comment by hetsch** [comment]
Thank you for your quick response. Yes, I tried that but the thing is that I can't find a runalias.exe in our SW 4.1.1 installation, neither does my colleague who is in charge of the whole project for much longer. Both of us thought that runalias.exe is version 5.x specific. So what I get from your answer is, that both SW versions (4 or 5) must have a runalias.exe installed by default and starting a session is only possible via the steps you described in your previous response. Thanks once again.

**Comment by gepaulwarwicker** [comment]
runalias.exe was introduced at 4.3 I think. If you only have 4.1 you will need to install 4.3 just to get the file. It will work at with earlier versions. Or just ask your local Smallworld support group to supply it.

**Comment by hetsch** [comment]
Everything makes sense now. I highly appreciate that you have taken your time to respond. Have a nice weekend!
