### ISSUE TITLE
VSIX file for the Extension

### ISSUE THREAD

**Issue by SwethaMukkavilly** [OpenSmallworld/magik-vscode#4]
Hi there,

Thanks for the extension. I am trying to set this up on the Development environment SW 4.x. As it is Citrix Server, we have restrictions on installing Node JS (it being a Windows 2012, not supported by Node JS).
Is VSIX installer for this extension an option (or) any alternatives for having Node JS installed on Windows Server 2012 ?

Thanks
Swetha

**Comment by ge-timothy-chueh** [comment]
VSIX file is now available in the root of the of the repository for offline installs. The extension is also available directly from the VS Code Marketplace if online connectivity is available.
https://github.com/OpenSmallworld/magik-vscode/blob/master/magik-vscode-0_2_3.vsix
https://marketplace.visualstudio.com/items?itemName=ge-smallworld.magik-vscode
